jsonHash[divHTML.id].c=[
    {
        "e": "STYLE",
        "id": "STYLEMain",
        "innerHTML": "",
        "style": {},
        "movetoparentxpath": "/html/head",
        "type": "text/css",
        "c": []
    },
    {
        "e": "DIV",
        "id": "divSplash",
        "style": {
            "position": "fixed",
            "left": "0%",
            "top": "0%",
            "width": "100%",
            "height": "100%"
        },
        "c": [
            {
                "e": "IFRAME",
                "id": "frameSplash",
                "style": {
                    "position": "absolute",
                    "left": "0%",
                    "top": "0%",
                    "width": "100%",
                    "height": "100%"
                },
                "src": "https://rawgit.com/markbrito/bouncechat/master/home.html"
            }
        ],
        "innerHTML": "&nbsp;&nbsp;",
        "contenteditable": "",
        "dropzone": ""
    },
    {
        "e": "DIV",
        "id": "divMain",
        "style": {
            "position": "fixed",
            "left": "15%",
            "top": "15%",
            "width": "70%",
            "height": "70%",
            "text-align": "center",
            "margin": "15px;"
        },
        "c": [
            {
                "e": "A",
                "id": "hrefResponsiveDesignHomePage",
                "innerHTML": "Responsive Design Home Page Rough Draft",
                "href": "https://cdn.rawgit.com/markbrito/webbuilder/master/bouncechat.html",
                "stylesheetid": "STYLEMain",
                "styleruletype": "Element",
                "style": {
                    "display": "block",
                    "margin": "5px",
                    "font-size": "15pt"
                },
                "target": "_blank"
            },
            {
                "e": "A",
                "id": "hrefNewDesignDemoOfMainPage",
                "style": {},
                "src": "New Design of Main Page",
                "innerHTML": "New%20Design%20Demo%20of%20HTML5%20Layout",
                "href": "Valid%20URL%20potentially%20surrounded%20by%20spaces",
                "target": "_blank"
            },
            {
                "e": "A",
                "id": "hreNewAutoGeneratedPagesFromPDF",
                "innerHTML": "All%20HTML%20pages%20generated%20via%20script%20from%20the%20PDF",
                "href": "http://dev.bouncechat.com/design/pages.html",
                "target": "_blank"
            },
            {
                "e": "A",
                "id": "hrefDevBuild",
                "innerHTML": "3D Demo",
                "href": "https://rawgit.com/markbrito/webGLColladaViewer/master/webDae12.html",
                "target": "_blank"
            },
            {
                "e": "A",
                "id": "href",
                "innerHTML": "WebBuilder",
                "href": "https://cdn.rawgit.com/markbrito/webbuilder/master/WebBuilder.html",
                "target": "_blank"
            },
            {
                "e": "A",
                "id": "hrefGitHubManager",
                "innerHTML": "GitHubManager (shadow ^37.*97)",
                "href": "https://cdn.rawgit.com/markbrito/webbuilder/master/gitmanager.html?key=f746dadf21cc63c353e37ca5cdc6bc70be51&test",
                "target": "_blank"
            }
        ]
    }
]
        "type": "text/css",
        "c": []
    },
    {
        "e": "DIV",
        "id": "divSplash",
        "style": {
            "position": "fixed",
            "left": "0%",
            "top": "0%",
            "width": "100%",
